package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Company | Leading India</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("function name1()\r\n");
      out.write("{\r\n");
      out.write(" var d=document.f1.fname.value;\r\n");
      out.write("if(document.f1.fname.value==\"\")\r\n");
      out.write("alert(\"Enter first name\");\r\n");
      out.write("  var i;\r\n");
      out.write("for(i=0;i<d.length;i++)\r\n");
      out.write("  {  \r\n");
      out.write("var temp=d.charAt(i);\r\n");
      out.write("var tt=new RegExp(\"^\\\\d$\") ;\r\n");
      out.write("if(tt.test(temp))\r\n");
      out.write("{\r\n");
      out.write("alert(\"Enter only character\");\r\n");
      out.write("break;\r\n");
      out.write("}}}\r\n");
      out.write("\r\n");
      out.write("function ans()\r\n");
      out.write("{\r\n");
      out.write(" var d=document.f1.sqans.value;\r\n");
      out.write("if(document.f1.sqans.value==\"\")\r\n");
      out.write("alert(\"Enter answer\");\r\n");
      out.write("  var i;\r\n");
      out.write("for(i=0;i<d.length;i++)\r\n");
      out.write("  {  \r\n");
      out.write("var temp=d.charAt(i);\r\n");
      out.write("var tt=new RegExp(\"^\\\\d$\") ;\r\n");
      out.write("if(tt.test(temp))\r\n");
      out.write("{\r\n");
      out.write("alert(\"Enter only character\");\r\n");
      out.write("break;\r\n");
      out.write("}}}\r\n");
      out.write("\r\n");
      out.write("function name2()\r\n");
      out.write("{\r\n");
      out.write(" d=document.f1.lname.value;\r\n");
      out.write("if(document.f1.lname.value==\"\")\r\n");
      out.write("alert(\"Enter last name\");\r\n");
      out.write("  var i;\r\n");
      out.write("for(i=0;i<d.length;i++)\r\n");
      out.write("  {  \r\n");
      out.write("var temp=d.charAt(i);\r\n");
      out.write("var tt=new RegExp(\"^\\\\d$\") ;\r\n");
      out.write("if(tt.test(temp))\r\n");
      out.write("{\r\n");
      out.write("alert(\"Enter only character\");\r\n");
      out.write("break;\r\n");
      out.write("}}}\r\n");
      out.write("\r\n");
      out.write("function age()\r\n");
      out.write("{\r\n");
      out.write("   if(document.f1.age.value==\"\")\r\n");
      out.write("     alert(\"Enter age\");\r\n");
      out.write("   else\r\n");
      out.write("    if(document.f1.age.value<25) \r\n");
      out.write("     alert(\"Enter age above 25 years\");\r\n");
      out.write("   var a=document.f1.age.value;\r\n");
      out.write("    var b=new RegExp(\"^\\\\d\\\\d$\") ;\r\n");
      out.write("  if(!b.test(a))\r\n");
      out.write("     alert(\"enter age in number\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function username()\r\n");
      out.write("{\r\n");
      out.write("var u=document.f1.uname.value;\r\n");
      out.write("if(u==\"\")\r\n");
      out.write("alert(\"enter username\");\r\n");
      out.write("else if(u.length<6)\r\n");
      out.write("alert(\"username should be minimum 6 characters\");\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function emp()\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("var x=document.f1.empid.value;\r\n");
      out.write("if(x==\"\")\r\n");
      out.write("alert(\"enter employee ID\");\r\n");
      out.write("atpos=x.indexOf(\"@\");\r\n");
      out.write("ashpos=x.IndexOf(\"#\");\r\n");
      out.write("if((atpos!=1 || ashpos!=7) && (atpos!=7 || ashpos!=1))\r\n");
      out.write("alert(\"Enter valid employee ID\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function email()\r\n");
      out.write("{\r\n");
      out.write("\t\r\n");
      out.write("var e=document.f1.mail.value;\r\n");
      out.write("if(e==\"\")\r\n");
      out.write("alert(\"enter mail ID\");\r\n");
      out.write("atpos=e.indexOf(\"@\");\r\n");
      out.write("dotpos=e.lastIndexOf(\".\");\r\n");
      out.write("if(atpos<1 || dotpos<atpos+1 || dotpos+3>=e.length)\r\n");
      out.write("alert(\"Enter valid email ID\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function password()\r\n");
      out.write("{\r\n");
      out.write("var l=document.f1.password.value;\r\n");
      out.write("if(l==\"\")\r\n");
      out.write("alert(\"Enter password\");\r\n");
      out.write("else if(l.length<6)\r\n");
      out.write("alert(\"password should be minimum 6 characters\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function confirm()\r\n");
      out.write("{\r\n");
      out.write("var c=document.f1.password1.value;\r\n");
      out.write("var l=document.f1.password.value;\r\n");
      out.write("if(l!=c)\r\n");
      out.write("alert(\"passwords don't match!!\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function gender()\r\n");
      out.write("{\r\n");
      out.write("if((!document.f1.gender[0].checked)&&(!document.f1.gender[1].checked))\r\n");
      out.write("alert(\"Choose any one gender\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check()\r\n");
      out.write("{\r\n");
      out.write("if((!document.f1.accept.checked))\r\n");
      out.write("alert(\"Accept the condition!\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function validate()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("name1();\r\n");
      out.write("name2();\r\n");
      out.write("age();\r\n");
      out.write("gender();\r\n");
      out.write("emp();\r\n");
      out.write("email();\r\n");
      out.write("password();\r\n");
      out.write("confirm();\r\n");
      out.write("ans();\r\n");
      out.write("check();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("} </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body\r\n");
      out.write("\tstyle=\"background-image: url('images/header1.png'); background-repeat: no-repeat;\">\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("<div id=\"heading\">\r\n");
      out.write("<h1 style=\"margin-left: 30px;\">Company | Leading India</h1>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"content\">\r\n");
      out.write("<div id=\"form1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form name=\"f1\" action=\"http://localhost:8080/TGMC/Signup\" method=\"get\">\r\n");
      out.write("<table>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>First Name</td>\r\n");
      out.write("\t\t<td><input type=\"text\" size=25 name=\"fname\"  /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Last Name</td>\r\n");
      out.write("\t\t<td><input type=\"text\" size=25 name=\"lname\"  /> <br />\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Age</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"age\"  ></input></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Gender</td>\r\n");
      out.write("\t\t<td><input type=\"radio\" name=\"gender\" value=\"Male\" >Male<input\r\n");
      out.write("\t\t\ttype=\"radio\" name=\"gender\" value=\"Female\" >Female</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Date of Birth</td>\r\n");
      out.write("\t\t<td><select name=\"day\">\r\n");
      out.write("\t\t\t<option value=\"00\">Date</option>\r\n");
      out.write("\t\t\t<option value=\"01\">1</option>\r\n");
      out.write("\t\t\t<option value=\"02\">2</option>\r\n");
      out.write("\t\t\t<option value=\"03\">3</option>\r\n");
      out.write("\t\t\t<option value=\"04\">4</option>\r\n");
      out.write("\t\t\t<option value=\"05\">5</option>\r\n");
      out.write("\t\t\t<option value=\"06\">6</option>\r\n");
      out.write("\t\t\t<option value=\"07\">7</option>\r\n");
      out.write("\t\t\t<option value=\"08\">8</option>\r\n");
      out.write("\t\t\t<option value=\"09\">9</option>\r\n");
      out.write("\t\t\t<option value=\"10\">10</option>\r\n");
      out.write("\t\t\t<option value=\"11\">11</option>\r\n");
      out.write("\t\t\t<option value=\"12\">12</option>\r\n");
      out.write("\t\t\t<option value=\"13\">13</option>\r\n");
      out.write("\t\t\t<option value=\"14\">14</option>\r\n");
      out.write("\t\t\t<option value=\"15\">15</option>\r\n");
      out.write("\t\t\t<option value=\"16\">16</option>\r\n");
      out.write("\t\t\t<option value=\"17\">17</option>\r\n");
      out.write("\t\t\t<option value=\"18\">18</option>\r\n");
      out.write("\t\t\t<option value=\"19\">19</option>\r\n");
      out.write("\t\t\t<option value=\"20\">20</option>\r\n");
      out.write("\t\t\t<option value=\"21\">21</option>\r\n");
      out.write("\t\t\t<option value=\"22\">22</option>\r\n");
      out.write("\t\t\t<option value=\"23\">23</option>\r\n");
      out.write("\t\t\t<option value=\"24\">24</option>\r\n");
      out.write("\t\t\t<option value=\"25\">25</option>\r\n");
      out.write("\t\t\t<option value=\"26\">26</option>\r\n");
      out.write("\t\t\t<option value=\"27\">27</option>\r\n");
      out.write("\t\t\t<option value=\"28\">28</option>\r\n");
      out.write("\t\t\t<option value=\"29\">29</option>\r\n");
      out.write("\t\t\t<option value=\"30\">30</option>\r\n");
      out.write("\t\t\t<option value=\"31\">31</option>\r\n");
      out.write("\t\t</select> <select name=\"month\">\r\n");
      out.write("\t\t\t<option value=\"00\">Month</option>\r\n");
      out.write("\t\t\t<option value=\"01\">JAN</option>\r\n");
      out.write("\t\t\t<option value=\"02\">FEB</option>\r\n");
      out.write("\t\t\t<option value=\"03\">MAR</option>\r\n");
      out.write("\t\t\t<option value=\"04\">APR</option>\r\n");
      out.write("\t\t\t<option value=\"05\">MAY</option>\r\n");
      out.write("\t\t\t<option value=\"06\">JUN</option>\r\n");
      out.write("\t\t\t<option value=\"07\">JUL</option>\r\n");
      out.write("\t\t\t<option value=\"08\">AUG</option>\r\n");
      out.write("\t\t\t<option value=\"09\">SEP</option>\r\n");
      out.write("\t\t\t<option value=\"10\">OCT</option>\r\n");
      out.write("\t\t\t<option value=\"11\">NOV</option>\r\n");
      out.write("\t\t\t<option value=\"12\">DEC</option>\r\n");
      out.write("\t\t</select> <select name=\"year\">\r\n");
      out.write("\t\t\t<option value=\"0000\">Year</option>\r\n");
      out.write("\t\t\t<option value=\"1970\">1970</option>\r\n");
      out.write("\t\t\t<option value=\"1971\">1971</option>\r\n");
      out.write("\t\t\t<option value=\"1972\">1972</option>\r\n");
      out.write("\t\t\t<option value=\"1973\">1973</option>\r\n");
      out.write("\t\t\t<option value=\"1974\">1974</option>\r\n");
      out.write("\t\t\t<option value=\"1975\">1975</option>\r\n");
      out.write("\t\t\t<option value=\"1976\">1976</option>\r\n");
      out.write("\t\t\t<option value=\"1977\">1977</option>\r\n");
      out.write("\t\t\t<option value=\"1978\">1978</option>\r\n");
      out.write("\t\t\t<option value=\"1979\">1979</option>\r\n");
      out.write("\t\t\t<option value=\"1980\">1980</option>\r\n");
      out.write("\t\t\t<option value=\"1981\">1981</option>\r\n");
      out.write("\t\t\t<option value=\"1982\">1982</option>\r\n");
      out.write("\t\t\t<option value=\"1983\">1983</option>\r\n");
      out.write("\t\t\t<option value=\"1984\">1984</option>\r\n");
      out.write("\t\t\t<option value=\"1985\">1985</option>\r\n");
      out.write("\t\t\t<option value=\"1986\">1986</option>\r\n");
      out.write("\t\t\t<option value=\"1987\">1987</option>\r\n");
      out.write("\t\t\t<option value=\"1988\">1988</option>\r\n");
      out.write("\t\t\t<option value=\"1989\">1989</option>\r\n");
      out.write("\t\t\t<option value=\"1990\">1990</option>\r\n");
      out.write("\t\t\t<option value=\"1991\">1991</option>\r\n");
      out.write("\t\t\t<option value=\"1992\">1992</option>\r\n");
      out.write("\t\t\t<option value=\"1993\">1993</option>\r\n");
      out.write("\t\t\t<option value=\"1994\">1994</option>\r\n");
      out.write("\t\t\t<option value=\"1995\">1995</option>\r\n");
      out.write("\t\t\t<option value=\"1996\">1996</option>\r\n");
      out.write("\t\t\t<option value=\"1997\">1997</option>\r\n");
      out.write("\t\t\t<option value=\"1998\">1998</option>\r\n");
      out.write("\t\t\t<option value=\"1999\">1999</option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Employee ID</td>\r\n");
      out.write("\t\t<td><input type=\"text\" size=7 name=\"empid\" /></td>\r\n");
      out.write("\t\t<td>Email-ID</td>\r\n");
      out.write("\t\t<td><input type=\"text\" size=25 name=\"mail\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Username</td>\r\n");
      out.write("\t\t<td><input type=\"text\" size=25 name=\"uname\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Password</td>\r\n");
      out.write("\t\t<td><input type=\"password\" size=25 name=\"password\" /></td>\r\n");
      out.write("\r\n");
      out.write("\t\t<td>Re-enter Password</td>\r\n");
      out.write("\t\t<td><input type=\"password\" size=25 name=\"password1\" /></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Secret Question</td>\r\n");
      out.write("\t\t<td><select name=\"sq\">\r\n");
      out.write("\t\t\t<option value=\"1\">Who is your favorite Actor?</option>\r\n");
      out.write("\t\t\t<option value=\"2\">What is name of the your birth place?</option>\r\n");
      out.write("\t\t\t<option value=\"3\">What is the name of your first teacher?</option>\r\n");
      out.write("\t\t</select></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>Answer</td>\r\n");
      out.write("\t\t<td><input type=\"text\" name=\"sqans\"></td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t \r\n");
      out.write("\t<td colspan=\"4\"><input type=\"checkbox\" name=\"accept\" /> I Hereby Declare that all the above mentioned details are true to my knowledge failing which actions can be taken against Me </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td colspan=\"4\">\r\n");
      out.write("\t\t<center><input type=\"submit\" value=\"Register\" onfocus=\"validate()\" style=\"background-color: #5C92E9; color: #fff;\"/></center>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\r\n");
      out.write("</table>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
